dist: trusty
language: python
python:
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database travis_testdb;' -U postgres
  - psql travis_testdb < schema.sql
  - cp tests/travis_config.yaml config.yaml
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install: "pip install -r requirements.txt"
script: pytest -vs