version: '3'

services:

  bot:
    build: .
    depends_on:
      - postgres
    environment:
      - JISHAKU_HIDE=1
    volumes:
      - ./:/app
    restart: always

  postgres:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:13-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
