version: '2'

services:

  bot:
    build: .
    depends_on:
      - postgres
    environment:
      - JISHAKU_HIDE=1
    volumes:
      - ./:/app

  postgres:
    image: postgres:10-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
