# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  "alpine 3.6":
    docker:
      - image: gorialis/discord.py:alpine-master
        environment:
          PGDATABASE: postgres
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: postgres

      - image: circleci/postgres:latest
        environment:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            pip install -U coverage flake8 isort pytest pytest-cov
            pip install -r requirements.txt

      - run:
          name: install psql
          command: |
            apk add --no-cache postgresql-client

      - run:
          name: wait for postgres..
          command: sleep 2

      - run:
          name: apply schema
          command: psql < schema.sql

      - run:
          name: run tests
          command: |
            cp .circleci/queuebot_config.yaml config.yaml
            export PYTHONPATH=$PYTHONPATH:$(pwd)
            pytest -vs --cov=queuebot --cov-report term-missing:skip-covered
            flake8 .
            isort . --check-only --recursive

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  build:
    jobs:
      - "alpine 3.6"
